<?php
declare(strict_types=1);

namespace MonkeysLegion\Cli\Command;

use MonkeysLegion\Cli\Console\Attributes\Command as CommandAttr;
use MonkeysLegion\Cli\Console\Command;

/**
 * Generate a blank migration file with up/down stubs.
 *
 * @copyright 2026 MonkeysCloud Team
 * @license   MIT
 */
#[CommandAttr('make:migration', 'Generate a blank migration file')]
final class MakeMigrationCommand extends Command
{
    use MakerHelpers;

    protected function handle(): int
    {
        $name = $this->argument(0) ?? $this->ask('Migration name (e.g., create_users_table):');

        if (trim($name) === '') {
            $this->error('Migration name is required.');

            return self::FAILURE;
        }

        // Sanitize name
        $name     = preg_replace('/[^a-zA-Z0-9_]/', '_', $name) ?? $name;
        $name     = strtolower(trim($name, '_'));
        $timestamp = date('Y_m_d_His');
        $className = 'M' . str_replace('_', '', $timestamp) . '_' . $this->toPascalCase($name);
        $fileName  = "M{$timestamp}_{$name}.php";

        $dir = $this->option('path');
        $dir = is_string($dir)
            ? $dir
            : (function_exists('base_path') ? base_path('database/migrations') : 'database/migrations');

        if (!is_dir($dir)) {
            mkdir($dir, 0o755, true);
        }

        $filePath = rtrim($dir, '/') . '/' . $fileName;

        $stub = <<<PHP
            <?php
            declare(strict_types=1);

            use MonkeysLegion\Database\Contracts\ConnectionInterface;

            /**
             * Migration: {$name}
             *
             * Generated by MonkeysLegion CLI on {$timestamp}.
             */
            return new class {
                public function up(ConnectionInterface \$db): void
                {
                    \$db->pdo()->exec(<<<'SQL'
                        -- UP: Add your migration SQL here
                    SQL);
                }

                public function down(ConnectionInterface \$db): void
                {
                    \$db->pdo()->exec(<<<'SQL'
                        -- DOWN: Reverse the migration here
                    SQL);
                }
            };

            PHP;

        file_put_contents($filePath, $stub);

        $this->info("✅ Migration created: {$fileName}");
        $this->comment("  Path: {$filePath}");

        return self::SUCCESS;
    }

    private function toPascalCase(string $str): string
    {
        return str_replace(' ', '', ucwords(str_replace('_', ' ', $str)));
    }
}
